"$schema": https://json-schema.org/draft/2020-12/schema
description: 'GeoSPARQL Geometry'
x-jsonld-context: ../../../geosparql.jsonld
type: object
properties:
  hasSize:
    type: object
  hasMetricSize:
    type: number
  hasLength:
    type: object
  hasMetricLength:
    type: number
  hasMetricSpatialResolution:
    type: number  
  hasPerimeterLength:
    type: object
  hasMetricPerimeterLength:
    type: number
  hasArea:
    type: object
  hasMetricArea:
    type: number
  hasVolume:
    type: object
  hasMetricVolume:
    type: number