"$schema": https://json-schema.org/draft/2020-12/schema
description: 'GeoSPARQL FeatureCollection'
x-jsonld-context: ../../../geosparql.jsonld
$defs:
  collection:
    type: object
    properties:
      member:
        type: array
        items:
          anyOf:
            - $ref: '#/$defs/collection'
            - $ref: '../feature/schema.yaml'
            - $ref: bblocks://ogc.ogc-utils.iri-or-curie