"$schema": https://json-schema.org/draft/2020-12/schema
description: 'GeoSPARQL FeatureCollection'
x-jsonld-context: ../../../geosparql.jsonld
allOf:
  - $ref: bblocks://ogc.geo.json-fg.featureCollection-lenient
  - type: object
    properties:
      properties:
        $ref: ../../properties/featureCollection/schema.yaml
      features:
        # this is a rdfs:member - but specified as features to fit the GeoJSON schema
        type: array
        items:
          oneOf:
            # Embedded observations
            - $ref: ../feature/schema.yaml
            # Ids/URIs
            - type: string