"$schema": https://json-schema.org/draft/2020-12/schema
description: 'GeoSAPRQL Geometry'
x-jsonld-context: ../../../geosparql.jsonld
type: object
allOf:
  - $ref:  bblocks://ogc.geo.json-fg.geometry-lenient
  - type: object
    properties:
      properties:
        $ref: ../../properties/geometry/schema.yaml