"$schema": https://json-schema.org/draft/2020-12/schema
description: 'GeoSPARQL Feature'
x-jsonld-context: ../../../geosparql.jsonld
type: object
properties:
  hasGeometry:
    type: object
  hasDefaultGeometry:
    type: object
  hasBoundingBox:
    type: object
  hasCentroid:
    type: object