"$schema": https://json-schema.org/draft/2020-12/schema
description: 'GeoSPARQL Geometry'
x-jsonld-context: ../../../geosparql.jsonld
type: object
properties:
  dimension:
    type: number
  coordinateDimension:
    type: number
  spatialDimension:
    type: number
  hasSpatialResolution:
    type: object
  hasMetricSpatialResolution:
    type: number  
  hasSpatialAccuracy:
    type: object
  hasMetricSpatialAccuracy:
    type: number
  isEmpty:
    type: boolean
  isSimple:
    type: boolean
  hasSerialization:
    type: object